ktor:
  application:
    modules:
      - org.srino.ApplicationKt.module
  deployment:
    port: 9090
  authentication:
    discord:
      clientId: "clientId"
      clientSecret: "secret"
    keys:
      sign: "sign"
      encrypt: "encrypt"