ktor:
  application:
    modules:
      - org.srino.ApplicationKt.module
  deployment:
    port: 8080
  database:
    url: "mongodb://srinoAdminPanelUser:xLvPEeStwHM09CHqQ779Full@88.151.194.171:27017/?authSource=SrinoAdminPanel"
    name: "SrinoAdminPanel"
  authentication:
    discord:
      clientId: "1439011001788928214"
      clientSecret: "0x_zbvgIjQw0k53MQvxDkDj4cRTR_ouq"
    keys:
      sign: "c099330798242487148cc2a3629e4f5b"
      encrypt: "33229bef265a8f76c70001f9e5dc2328"
  debugging: true